TEXTS = {
    "ru": {
        "title": "# Flux Prompt Lab: идея → промпт",
        "idea_label": "Ваша идея",
        "idea_placeholder": "Например: киберпанк, дождливая улица с неоном",
        "slider_label": "Креативность (0 = строго по идее, 10 = креативно)",
        "generate": "Сгенерировать",
        "creative": "Креатив",
        "save_name": "Имя для сохранения",
        "save_btn": "Сохранить промпт",
        "saved_prompts": "Сохранённые записи",
        "load_btn": "Загрузить",
        "refresh_btn": "Обновить список",
        "delete_btn": "Удалить",
        "prompt_editor": "Промпт (редактируемый)",
        "status": "Статус",
        "copy_button_html": " <button onclick=\"navigator.clipboard.writeText(document.getElementById('prompt_editor').value)\">Копировать</button> ",
        "switch_lang": "EN",
    },
    "en": {
        "title": "# Flux Prompt Lab: idea → prompt",
        "idea_label": "Your idea",
        "idea_placeholder": "Eg: cyberpunk, rainy neon street",
        "slider_label": "Creativity (0 = literal, 10 = creative)",
        "generate": "Generate",
        "creative": "Creative",
        "save_name": "Save name",
        "save_btn": "Save prompt",
        "saved_prompts": "Saved prompts",
        "load_btn": "Load",
        "refresh_btn": "Refresh list",
        "delete_btn": "Delete",
        "prompt_editor": "Prompt (editable)",
        "status": "Status",
        "copy_button_html": " <button onclick=\"navigator.clipboard.writeText(document.getElementById('prompt_editor').value)\">Copy</button> ",
        "switch_lang": "RU",
    },
}
